#!/usr/bin/env bash
# Open the /etc/passwd file for reading
exec 3< /etc/passwd

while IFS=":" read -r username _ uid gid _ home shell
do
    # Retrieve additional information from /etc/passwd file
    info=$(grep -w "$username" /etc/passwd | cut -d: -f5)

    # Retrieve the password from /etc/shadow file
    password=$(grep -w "$username" /etc/shadow | cut -d: -f2)

    echo "The user $username is part of the group with ID $gid, lives in $home, and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $info."
    echo
done <&3

# Close the file descriptor
exec 3<&-
