#!/usr/bin/env bash
#groups visistors by IP and HTT Use awk to group visitors by IP and HTTP status code, count occurrences, and print the data
awk ' {print $1,$9}' apache-access.log | sort |	uniq -c | sort -rn
