#!/usr/bin/env bash
#best school 10 times for 9nth display hi on a new line
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    counter=$((counter+1))
done
