#!/usr/bin/env bash
#bad luck at the4th good at 8th best for the others

counter=1
while [ $counter -le 10 ]
do 
	if [ $counter -eq 4 ]
	then 
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
