#!/usr/bin/env bash
#clock
hour=0
minute=1

while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    
    while [ $minutes -le 59 ]; do
        echo $minutes
        ((minutes++))
    done

    ((hours++))
    minutes=1
done
