#!/usr/bin/env bash
#do all in the instructions


#creates /var/run/myscript.pid containing its pid
echo $$ > /var/run/myscript.pid

#diplays to I hate to kill command
sigterm_handler(){
        echo "I hate the kill command"
	exit 0
}       



#displays Y U NO LOVE ME 
sigint_handler(){
        echo "Y U no love me?!"
}

#register the signal handlder functions
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT


#Displays to infinity and beyond indefinetely
while :
do
	echo "To infinity and beyond"
	sleep 2
done



#last directives
rm /var/run/myscript.pid
exit 0
