#!/usr/bin/env bash
#last project this one is managing manage_my_process

start_manage_my_process() {
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"
}

stop_manage_my_process() {
  if [[ -f "/var/run/my_process.pid" ]]; then
    pid=$(cat /var/run/my_process.pid)
    if kill "$pid"; then
      rm -f /var/run/my_process.pid
      echo "manage_my_process stopped"
    else
      echo "Failed to stop manage_my_process"
    fi
  else
    echo "manage_my_process is not running"
  fi
}

restart_manage_my_process() {
  stop_manage_my_process
  start_manage_my_process
  echo "manage_my_process restarted"
}

case "$1" in
  start)
    start_manage_my_process
    ;;
  stop)
    stop_manage_my_process
    ;;
  restart)
    restart_manage_my_process
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
