#!/usr/bin/env bash
#Do the same as 4 but displays I am invincible when a sigterm is received
i=0
while [ $i -le 3]
do 
	trap echo "I am invicible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done 
